# Generated by Django 6.0.1 on 2026-01-09 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=200)),
                ('julukan', models.CharField(blank=True, help_text='Nama panggilan atau julukan', max_length=100, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor Telepon')),
                ('status', models.CharField(choices=[('active', 'Active'), ('blacklist', 'Blacklist')], default='blacklist', max_length=20)),
            ],
            options={
                'verbose_name': 'Agen',
                'verbose_name_plural': 'Agen',
                'db_table': 'agen',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distrik', models.CharField(max_length=100)),
                ('lokasi_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Lokasi',
                'verbose_name_plural': 'Lokasi',
                'db_table': 'lokasi',
                'ordering': ['distrik', 'lokasi_name'],
            },
        ),
        migrations.CreateModel(
            name='Pemilik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=200)),
                ('no_telp', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor Telepon')),
                ('status', models.CharField(choices=[('active', 'Active'), ('blacklist', 'Blacklist')], default='blacklist', max_length=20)),
            ],
            options={
                'verbose_name': 'Pemilik',
                'verbose_name_plural': 'Pemilik',
                'db_table': 'pemilik',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Gedung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama_gedung', models.CharField(blank=True, help_text='Nama gedung (opsional)', max_length=200, null=True)),
                ('lat', models.DecimalField(decimal_places=15, help_text='Contoh: 30.065958719470665', max_digits=17, verbose_name='Latitude')),
                ('long', models.DecimalField(decimal_places=15, help_text='Contoh: 31.327724660547236', max_digits=18, verbose_name='Longitude')),
                ('alamat', models.TextField()),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gedungs', to='core.lokasi')),
            ],
            options={
                'verbose_name': 'Gedung',
                'verbose_name_plural': 'Gedung',
                'db_table': 'gedung',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_number', models.CharField(max_length=50, verbose_name='Nomor Unit')),
                ('listing_type', models.CharField(choices=[('available', 'Available'), ('blacklist', 'Blacklist')], default='blacklist', max_length=20)),
                ('alasan_blacklist', models.TextField(blank=True, null=True, verbose_name='Alasan Blacklist')),
                ('agen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='core.agen')),
                ('gedung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.gedung')),
                ('pemilik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='core.pemilik')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Unit',
                'db_table': 'unit',
                'ordering': ['gedung', 'unit_number'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(help_text='Upload gambar gedung atau unit', upload_to='images/%Y/%m/%d/')),
                ('is_primary', models.BooleanField(default=False, help_text='Centang jika ini gambar utama', verbose_name='Gambar Utama')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('gedung', 'unit')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'image',
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='image_content_299c2e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='gedung',
            index=models.Index(fields=['lat', 'long'], name='gedung_lat_0a2239_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('gedung', 'unit_number')},
        ),
    ]
