# Generated by Django 6.0.1 on 2026-01-10 00:53

import apps.core.utils
import apps.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gedung',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='Upload gambar gedung atau unit', upload_to=apps.core.utils.image_upload_path, validators=[apps.core.validators.validate_image_file]),
        ),
    ]
