# Generated by Django 6.0.1 on 2026-01-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gedung_uuid_alter_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['gedung', 'lantai', 'unit_number'], 'verbose_name': 'Unit', 'verbose_name_plural': 'Unit'},
        ),
        migrations.AddField(
            model_name='unit',
            name='lantai',
            field=models.PositiveIntegerField(default=1, help_text='Lantai unit', verbose_name='Lantai'),
            preserve_default=False,
        ),
    ]
