# Generated by Django 6.0.1 on 2026-01-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_unit_options_unit_lantai'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemilik',
            name='julukan',
            field=models.CharField(blank=True, help_text='Nama panggilan atau julukan', max_length=100, null=True, verbose_name='Julukan (opsional)'),
        ),
        migrations.AlterField(
            model_name='agen',
            name='julukan',
            field=models.CharField(blank=True, help_text='Nama panggilan atau julukan', max_length=100, null=True, verbose_name='Julukan (opsional)'),
        ),
        migrations.AlterField(
            model_name='agen',
            name='no_telp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor Telepon (opsional)'),
        ),
        migrations.AlterField(
            model_name='pemilik',
            name='no_telp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor Telepon (opsional)'),
        ),
    ]
