# Generated by Django 6.0.1 on 2026-01-10 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pemilik_julukan_alter_agen_julukan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distrik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=100, unique=True, verbose_name='Nama Distrik')),
                ('kode', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Kode Distrik (opsional)')),
            ],
            options={
                'verbose_name': 'Distrik',
                'verbose_name_plural': 'Distrik',
                'db_table': 'distrik',
                'ordering': ['nama'],
            },
        ),
        migrations.AlterModelOptions(
            name='lokasi',
            options={'ordering': ['distrik__nama', 'nama'], 'verbose_name': 'Lokasi', 'verbose_name_plural': 'Lokasi'},
        ),
        migrations.AddField(
            model_name='lokasi',
            name='nama',
            field=models.CharField(default=1, max_length=200, verbose_name='Nama Lokasi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lokasi',
            name='distrik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lokasis', to='core.distrik'),
        ),
        migrations.AlterUniqueTogether(
            name='lokasi',
            unique_together={('distrik', 'nama')},
        ),
        migrations.RemoveField(
            model_name='lokasi',
            name='lokasi_name',
        ),
    ]
