# Generated by Django 6.0.1 on 2026-01-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_distrik_alter_lokasi_options_lokasi_nama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='deskripsi',
            field=models.TextField(default=1, help_text='Contoh: Sebelah kanan, Pintu teralis, di tengah', verbose_name='Deskripsi'),
            preserve_default=False,
        ),
    ]
