# Generated by Django 6.0.1 on 2026-01-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_unit_deskripsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='deskripsi',
            field=models.CharField(help_text='Contoh: Sebelah kanan, Pintu teralis, di tengah', max_length=50, verbose_name='Deskripsi'),
        ),
    ]
