# Generated by Django 6.0.1 on 2026-01-11 01:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_unit_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
